server:
  port: 8889
spring:
  application:
    name: gateway-service-zuul1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
zuul:
  prefix: /appservice