server:
  port: 9002
spring:
  application:
    name: client1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
feign: 
  hystrix: 
    enabled: true