server:
  port: 9001
spring:
  application:
    name: producer-2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
management:
  security:
    enabled: false